// AUTO-GENERATED by tauri-specta — DO NOT EDIT MANUALLY
// Regenerated on every `pnpm tauri dev` run
//
// If this file is empty or missing, run: pnpm tauri dev
// and it will be generated at src/lib/bindings.ts

import { invoke } from '@tauri-apps/api/core';
import { Channel } from '@tauri-apps/api/core';

export type StreamEvent =
  | { event: 'token'; data: { text: string } }
  | { event: 'done'; data: null }
  | { event: 'error'; data: { message: string } };

export async function setApiKey(args: { provider: string; key: string }): Promise<void> {
  return await invoke('set_api_key', args);
}

export async function getApiKeyStatus(args: {
  provider: string;
}): Promise<{ configured: boolean }> {
  return await invoke('get_api_key_status', args);
}

export async function deleteApiKey(args: { provider: string }): Promise<void> {
  return await invoke('delete_api_key', args);
}

export async function streamLlmDemo(args: {
  prompt: string;
  onEvent: Channel<StreamEvent>;
}): Promise<void> {
  return await invoke('stream_llm_demo', args);
}
