// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	setApiKey: (provider: string, key: string) => typedError<null, string>(__TAURI_INVOKE("set_api_key", { provider, key })),
	getApiKeyStatus: (provider: string) => typedError<ApiKeyStatus, string>(__TAURI_INVOKE("get_api_key_status", { provider })),
	deleteApiKey: (provider: string) => typedError<null, string>(__TAURI_INVOKE("delete_api_key", { provider })),
	/**
	 *  Demo command — validates the Channel API pattern works end-to-end.
	 *  Phase 2 replaces this with real LLM streaming via reqwest.
	 *  The function signature and Channel<StreamEvent> usage are the canonical template.
	 *  T-01-04-01: bounded by prompt word count; Phase 2 must add max-token guard.
	 */
	streamLlmDemo: (prompt: string, onEvent: Channel<StreamEvent>) => typedError<null, string>(__TAURI_INVOKE("stream_llm_demo", { prompt, onEvent })),
};

/* Types */
export type ApiKeyStatus = {
	configured: boolean,
};

/**
 *  StreamEvent is the CANONICAL event type for all streaming in NexusAI.
 *  Phase 2+ must use this enum (or extend it) for all LLM token streaming.
 *  NEVER use app.emit() in a loop — see RESEARCH.md §Anti-Patterns.
 */
export type StreamEvent = { event: "token"; data: {
	text: string,
} } | { event: "done" } | { event: "error"; data: {
	message: string,
} };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

