import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';

// Phase 1: metadata table — records last-seen schema version
// Future phases add their own tables in new migration files
export const schemaMeta = sqliteTable('schema_meta', {
  id: integer('id').primaryKey(),
  version: text('version').notNull(),
  appliedAt: integer('applied_at', { mode: 'timestamp' }).notNull(),
});

// Re-export all tables for use in runMigrations type checking
export type SchemaMeta = typeof schemaMeta.$inferSelect;
export type NewSchemaMeta = typeof schemaMeta.$inferInsert;

// Phase 2: LLM Chat tables

export const conversations = sqliteTable('conversations', {
  id: text('id').primaryKey(), // UUID generated by frontend (crypto.randomUUID())
  title: text('title').notNull().default('Nova Conversa'),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull(),
  deletedAt: integer('deleted_at', { mode: 'timestamp' }), // D-30: soft-delete
  lastModel: text('last_model'), // D-03: model badge in conversation list
});

export const messages = sqliteTable('messages', {
  id: text('id').primaryKey(), // UUID
  conversationId: text('conversation_id')
    .notNull()
    .references(() => conversations.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['user', 'assistant'] }).notNull(),
  content: text('content').notNull(),
  model: text('model'), // D-20: per-message model tracking (null for user messages)
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
  deletedAt: integer('deleted_at', { mode: 'timestamp' }), // D-30: soft-delete
});

export const attachments = sqliteTable('attachments', {
  id: text('id').primaryKey(), // UUID
  messageId: text('message_id')
    .notNull()
    .references(() => messages.id, { onDelete: 'cascade' }),
  filename: text('filename').notNull(),
  mimeType: text('mime_type').notNull(),
  filePath: text('file_path').notNull(), // Absolute path in Tauri app data dir
  fileSizeBytes: integer('file_size_bytes').notNull(),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull(),
});

// Type exports for use in stores and API layers
export type Conversation = typeof conversations.$inferSelect;
export type NewConversation = typeof conversations.$inferInsert;
export type Message = typeof messages.$inferSelect;
export type NewMessage = typeof messages.$inferInsert;
export type Attachment = typeof attachments.$inferSelect;
export type NewAttachment = typeof attachments.$inferInsert;
