/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as McpIndexRouteImport } from './routes/mcp/index'
import { Route as KbIndexRouteImport } from './routes/kb/index'
import { Route as GmailIndexRouteImport } from './routes/gmail/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as BenchmarkIndexRouteImport } from './routes/benchmark/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsApiKeysRouteImport } from './routes/settings/api-keys'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const McpIndexRoute = McpIndexRouteImport.update({
  id: '/mcp/',
  path: '/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const KbIndexRoute = KbIndexRouteImport.update({
  id: '/kb/',
  path: '/kb/',
  getParentRoute: () => rootRouteImport,
} as any)
const GmailIndexRoute = GmailIndexRouteImport.update({
  id: '/gmail/',
  path: '/gmail/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkIndexRoute = BenchmarkIndexRouteImport.update({
  id: '/benchmark/',
  path: '/benchmark/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/models': typeof SettingsModelsRoute
  '/agents/': typeof AgentsIndexRoute
  '/benchmark/': typeof BenchmarkIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/gmail/': typeof GmailIndexRoute
  '/kb/': typeof KbIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/models': typeof SettingsModelsRoute
  '/agents': typeof AgentsIndexRoute
  '/benchmark': typeof BenchmarkIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/chat': typeof ChatIndexRoute
  '/gmail': typeof GmailIndexRoute
  '/kb': typeof KbIndexRoute
  '/mcp': typeof McpIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/models': typeof SettingsModelsRoute
  '/agents/': typeof AgentsIndexRoute
  '/benchmark/': typeof BenchmarkIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/gmail/': typeof GmailIndexRoute
  '/kb/': typeof KbIndexRoute
  '/mcp/': typeof McpIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/settings'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/models'
    | '/agents/'
    | '/benchmark/'
    | '/calendar/'
    | '/chat/'
    | '/gmail/'
    | '/kb/'
    | '/mcp/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/models'
    | '/agents'
    | '/benchmark'
    | '/calendar'
    | '/chat'
    | '/gmail'
    | '/kb'
    | '/mcp'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/settings'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/models'
    | '/agents/'
    | '/benchmark/'
    | '/calendar/'
    | '/chat/'
    | '/gmail/'
    | '/kb/'
    | '/mcp/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  AgentsIndexRoute: typeof AgentsIndexRoute
  BenchmarkIndexRoute: typeof BenchmarkIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  GmailIndexRoute: typeof GmailIndexRoute
  KbIndexRoute: typeof KbIndexRoute
  McpIndexRoute: typeof McpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/mcp/': {
      id: '/mcp/'
      path: '/mcp'
      fullPath: '/mcp/'
      preLoaderRoute: typeof McpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/': {
      id: '/kb/'
      path: '/kb'
      fullPath: '/kb/'
      preLoaderRoute: typeof KbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmail/': {
      id: '/gmail/'
      path: '/gmail'
      fullPath: '/gmail/'
      preLoaderRoute: typeof GmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark/': {
      id: '/benchmark/'
      path: '/benchmark'
      fullPath: '/benchmark/'
      preLoaderRoute: typeof BenchmarkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface SettingsRouteChildren {
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  AgentsIndexRoute: AgentsIndexRoute,
  BenchmarkIndexRoute: BenchmarkIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  GmailIndexRoute: GmailIndexRoute,
  KbIndexRoute: KbIndexRoute,
  McpIndexRoute: McpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
